# Site settings
course_name: Trustworthy AI Systems
course_description: " Welcome to Trustworthy AI Systems! In this course, we will cover learning-based modern AI 
Systems with exemplary topics in computer vision, natural language processing, and speech systems. Meanwhile, 
we will discuss how to design AI systems that people can trust—systems that are transparent, fair, secure, 
private, robust, and capable of making decisions that positively impact society. You will develop not just 
technical expertise but also a mindset that embraces critical thinking, ethical reasoning, and a commitment 
to lifelong learning. By the end of this course, you will sharpen your problem-solving abilities by tackling 
real-world AI challenges. Your communication skills will be enhanced as you learn to explain complex technical 
concepts to diverse audiences. As we stand in a new era of AI, the need for systems that are not only intelligent 
but also reliable, ethical, and secure has never been more urgent. Let us embark on this journey together to build a 
future where AI enhances the human experience!
"
course_semester: "Fall 2024"

baseurl: "/CIS6930" # the subpath of your site, e.g. /blog/
url: "https://myrespect.github.io/" # the base hostname & protocol for your site

schoolname: "University of South Florida"
schoolurl: "https://usf.edu"
twitter_username: 

address: |
    Department of Computer Science
    University of South Florida
    Tampa, Florida

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
